# Slice indexing:

Similar to the use of slice indexing with lists and strings, we can use slice indexing to pull out sub-regions of ndarrays.

In [1]:
import numpy as np

In [2]:
a=np.arange(1,21).reshape(5,4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [3]:
#if we want to extract last row
a[-1]

array([17, 18, 19, 20])

In [5]:
#if we want to extract zero row
a[0]

array([1, 2, 3, 4])

In [7]:
#if we want to extract first coloumn
a[:,1]            before : indicate we want all rows in coloumn first

array([ 2,  6, 10, 14, 18])

In [9]:
#if we want to extract 5,6,9,10 coloumn
a[1:3,0:2]       #1:3 indicate rows, 0:2 indicate coloumns

array([[ 5,  6],
       [ 9, 10]])

In [10]:
a[::-1]                #reverse the array

array([[17, 18, 19, 20],
       [13, 14, 15, 16],
       [ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [15]:
print(a)
a[2:,3]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


array([12, 16, 20])

In [20]:
a[2,:3]

array([ 9, 10, 11])

In [21]:
a[2,1:3]

array([10, 11])

In [22]:
a[2:,1:3]

array([[10, 11],
       [14, 15],
       [18, 19]])

# Boolean Indexing