# Numpy

NumPy stands for numeric python which is a python package for the computation and processing of the multidimensional and single dimensional array elements.

numpy : a  high level data science library/API for storing ,retrieval and manipulation of large numeric datasets and operations associated with numeric data


Numpy main object is the multidimensional array.

## Advantages

# Array

In [ ]:
# Numpy : It works with dimensionality data 

## Basic Numpy

In [ ]:
#difference between list and numpy

In [3]:
a=[1,2,3,4]
print(a)
print(type(a))

print(len(a))
print(a.shape)

[1, 2, 3, 4]
<class 'list'>
4


AttributeError: 'list' object has no attribute 'shape'

In [ ]:
# list is a scalar = there is no dims for the list 

## Array method in numpy

In [5]:
import numpy as np

In [6]:
## array is used to create the dimensions

In [7]:
#1 D array

a=np.array([1,2,3,4])
print(a)

print(type(a))
print(a.ndim)     # keyword is used for finding the dimensions 


[1 2 3 4]
<class 'numpy.ndarray'>
1


### Note- ndim keyword is used for finding the dimensions. 


In [8]:
#let's understand about dims

In [9]:
# 2D array

ab=np.array([[1,2,3,4] , [5,6,7,8]])
print(a)

print(type(ab))
print(ab.shape)  #shape keyword is used to find the size of array       #(2,4) means 2 rows 4 colomns
print(ab.ndim)      #2 means 2 dimensinal array

[1 2 3 4]
<class 'numpy.ndarray'>
(2, 4)
2


In [10]:
#3D array

a = np.array([[[1,2,3,4] , [5,6,7,8]]])
print(a)
print(type(a))
print(a.shape)    #shape keyword is used to find the size of array
print(a.ndim)      #3 means 3 dimensional array

[[[1 2 3 4]
  [5 6 7 8]]]
<class 'numpy.ndarray'>
(1, 2, 4)
3


### Note- shape keyword is used to find the size of array

In [11]:
a=np.array([[[3,5,6,8]]])
print(a)
print(type(a))
print(a.shape)    #shape keyword is used to find the size of array
print(a.ndim)

print("\nMemory size of a NumPy array in bytes :",a.nbytes)   #Memory size of a NumPy array in bytes

print("\nSize of the array :",a.size)      #size keyword is used to find how many number of values are there 

     
print("\nMemory size of one array element in bytes :",a.itemsize)     #Memory size of one array element in bytes

print("\nMemory size of numpy array in bytes :",a.size*a.itemsize)  #Memory size of numpy array in bytes

[[[3 5 6 8]]]
<class 'numpy.ndarray'>
(1, 1, 4)
3

Memory size of a NumPy array in bytes : 16

Size of the array : 4

Memory size of one array element in bytes : 4

Memory size of numpy array in bytes : 16


### Note-

1. nbytes keyword is used directly to find Memory size of a NumPy array in bytes.

2. size keyword is used to find how many number of values are there. 

3. itemsize keyword is used to find Memory size of one array element in bytes.

4. size*itemsize is used to find Memory size of numpy array in bytes.

     

In [12]:
#how much memory needed for the variable to occpy in memory space- 32,64

In [13]:

a=np.array([[1,4,6,8],[8,67,45,3]])
print(a)

print(a.nbytes)

[[ 1  4  6  8]
 [ 8 67 45  3]]
32


In [14]:
a=np.array([[1,4,6,8],[8,67,45,3]],dtype=np.int64)    #with the help pf dtype we change its size, but default size is float.
print(a)

print(a.nbytes)

[[ 1  4  6  8]
 [ 8 67 45  3]]
64


### Note- dtype keyword is used to change the memory size 

In [15]:
a=np.array([[34,6,7],[8,7,9]])
a

array([[34,  6,  7],
       [ 8,  7,  9]])

In [16]:
#if we want 9

print(a[1][2])   

9


#Explain
It has 2rows and 3 coloumns

firstly we we see where 9 is, 9 in row 1 that's why we write a[1], now we see in row 1 the position of 9 is 2 that's why we wrire [2]

In [17]:
a = np.array([[11,12,14] , ["a" , 2 , 'c'] , [49.1,44.5,9.0]])
print(a)

print(type(a))
print("\nnumber of dims = " , a.ndim)
print("\nMemory space=",a.nbytes)

[['11' '12' '14']
 ['a' '2' 'c']
 ['49.1' '44.5' '9.0']]
<class 'numpy.ndarray'>

number of dims =  2

Memory space= 1152


In [18]:
a = np.array([[[11,12,14] , ["a" , 2 , 'c'] , [49.1,44.5,9.0]]])
print(a)

print(type(a))
print(a.shape)
print("\nnumber of dims = " , a.ndim)
print("\nMemory space=",a.nbytes)

[[['11' '12' '14']
  ['a' '2' 'c']
  ['49.1' '44.5' '9.0']]]
<class 'numpy.ndarray'>
(1, 3, 3)

number of dims =  3

Memory space= 1152


# arange()

In [19]:
# for single dimensions there is a method in numpy called = arange 


In [20]:
a=np.arange(1,10)      #follow n-1 concept #(Starting num,end num-1)
print(a)
print(a.ndim)

print("\ntype=",type(a))

[1 2 3 4 5 6 7 8 9]
1

type= <class 'numpy.ndarray'>


In [21]:
a=np.arange(1,10,2)  #last perimeter is step size , giving the gap of two numbers
print(a)

[1 3 5 7 9]


In [22]:
# using data type

a=np.arange(1,10,2,dtype=int)
print(a)

print(a.nbytes)

[1 3 5 7 9]
20


In [23]:
a=np.arange(1,10,2,dtype=float)
print(a)

print(a.nbytes)

[1. 3. 5. 7. 9.]
40


In [24]:
a=np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [25]:
a=np.arange(1,10)
print(a)
a[6:]=50
print(a)

[1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6 50 50 50]


In [26]:
#using slicing operation
a=np.arange(10,20)
print("before=",a)
ab=a[::-1]
print("after",ab)

before= [10 11 12 13 14 15 16 17 18 19]
after [19 18 17 16 15 14 13 12 11 10]


# linspace()

linespace is used to brreak the range into pieces:this not follows (n-1) stuff.


Return evenly spaced numbers over a specified interval.

Returns num evenly spaced samples, calculated over the interval [start, stop]

In [27]:
a=np.linspace(2,10,4)
print(a)

[ 2.          4.66666667  7.33333333 10.        ]


In [28]:
a=np.linspace(2,20,8)    #start =2 , stop=20
print(a)

[ 2.          4.57142857  7.14285714  9.71428571 12.28571429 14.85714286
 17.42857143 20.        ]


In [29]:
a=np.linspace(2,20,8,endpoint=True)
print(a)

[ 2.          4.57142857  7.14285714  9.71428571 12.28571429 14.85714286
 17.42857143 20.        ]


In [30]:
a=np.linspace(2,20,8,endpoint=False)           #default=true
print(a)

[ 2.    4.25  6.5   8.75 11.   13.25 15.5  17.75]


In [31]:
a=np.linspace(2,20,8,retstep=False)           #default=false
print(a)

[ 2.          4.57142857  7.14285714  9.71428571 12.28571429 14.85714286
 17.42857143 20.        ]


In [32]:
a=np.linspace(2,20,8,retstep=True)           #how much space is taken
print(a)

(array([ 2.        ,  4.57142857,  7.14285714,  9.71428571, 12.28571429,
       14.85714286, 17.42857143, 20.        ]), 2.5714285714285716)


# Zeros()

Return a new array of given shape and type, filled with zeros.

In [33]:


a=np.zeros(5)
print(a)
print(a.ndim)

[0. 0. 0. 0. 0.]
1


In [34]:
a=np.zeros(5,dtype=int)
print(a)

[0 0 0 0 0]


In [35]:

a=np.zeros((5,8))
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [36]:
a=np.zeros((5,3,2),dtype=int)
print(a)

[[[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]]


# ones()

Return a new array of given shape and type, filled with ones.

In [37]:
a=np.ones(6)
print(a)

[1. 1. 1. 1. 1. 1.]


In [38]:
a=np.ones(6,dtype=int)
print(a)

[1 1 1 1 1 1]


In [39]:
a=np.ones((4,7))
print(a)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [40]:
a=np.ones((2,4,3))
print(a)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


# Random concept

Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

In [41]:
# randint = used to select a random integer value 

np.random.seed(11)  # this line used to keep stable outcome 

# seed -------->randint  
     


np.random.randint(10,20)

19

In [42]:
# rand=gives values from 0 to 1:  random values

a=np.random.rand(4,4)   # randomlly 3 rows and 4 columns created 
print(a)

[[0.06830684 0.66472032 0.19411562 0.92628296]
 [0.10517516 0.22571272 0.89634075 0.82618135]
 [0.09281249 0.88970819 0.71376193 0.51789854]
 [0.78538872 0.58766585 0.73683621 0.67251024]]


In [43]:
a=np.random.rand(5)
print(a)

[0.97007099 0.98857911 0.7781032  0.02514928 0.92127874]


In [44]:
# randn = works with standard devitaltion concept : dont worry just small change coompare to randn

a=np.random.randn(4,6) 
print(a)

[[-1.27147013 -0.36504469  0.39154076 -0.318382    0.4417959  -0.55436174]
 [ 1.5023821  -0.08958725  0.12593849 -0.47256745  0.92555968 -0.13389511]
 [ 0.0114951  -0.77089861  1.97127672 -0.38668093 -2.70551241 -0.55119021]
 [-0.50050111 -0.1114592  -0.10875487 -1.40320603  0.22448369  0.5359486 ]]


In [45]:
a=np.random.random((4,6))
print(a)

[[0.9882568  0.4696408  0.82353614 0.05068039 0.74390587 0.2632371 ]
 [0.97713662 0.66548802 0.9939018  0.32010281 0.78901697 0.21480359]
 [0.95110795 0.33474034 0.50177261 0.72056553 0.37191634 0.15856975]
 [0.05442761 0.65078059 0.04019312 0.22806536 0.45741168 0.28448009]]


## Difference between randn and rand

numpy.random.randn generates samples from the normal distribution, while numpy.random.rand from uniform (in range [0,1)).

# Note---

for numpy  axis = 1 means rows and axis = 0 means columns 
for pandas   axis = 0 means rows and axis = 1 means columns 

# Seed function

In [125]:
np.random.seed(12)
arr=np.random.randint(1,100,10)
print(arr)

[76 28  7  3  4 68 77 49 23 50]


In [127]:
np.random.seed(2)
arr=np.random.randint(1,100,10)
print(arr)

[41 16 73 23 44 83 76  8 35 50]


In [130]:
arr=np.random.randint(1,100,10)
print(arr)

[69 47 71 96 84 32 67 81 53 77]


In [138]:
np.random.seed(2)
arr=np.random.randn(1,10)
print(arr)

[[-0.41675785 -0.05626683 -2.1361961   1.64027081 -1.79343559 -0.84174737
   0.50288142 -1.24528809 -1.05795222 -0.90900761]]


# Conversion of array

In [46]:
#from 1D to 2D

a=np.arange(1,21)
print(a)

print(a.ndim)        #find the dimension

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
1


In [47]:
ab=np.arange(1,21).reshape(5,4)      
print(ab)

print(ab.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
2


### Note-- reshape keyword is used to change the shape of array.

In [48]:
#pull out the value 11

ab[2][2]

11

In [49]:
#pull out 19
ab[4][2]

19

In [50]:
# convert 1d to 3d and pull value out 

b=np.arange(1,41)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40]


In [51]:
b=np.arange(1,41).reshape(2,2,10)          #2*2*10=40
print(b)

print(b.ndim)

[[[ 1  2  3  4  5  6  7  8  9 10]
  [11 12 13 14 15 16 17 18 19 20]]

 [[21 22 23 24 25 26 27 28 29 30]
  [31 32 33 34 35 36 37 38 39 40]]]
3


In [52]:
#pull out 24

b[1][0][3]

24

In [53]:
# we can check sum of the array also
np.sum(b,axis=1)             # 1 is for row wise

array([[12, 14, 16, 18, 20, 22, 24, 26, 28, 30],
       [52, 54, 56, 58, 60, 62, 64, 66, 68, 70]])

In [54]:

np.sum(b,axis=0)             # 0 is for coloumn wise

array([[22, 24, 26, 28, 30, 32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50, 52, 54, 56, 58, 60]])

In [55]:
np.sum(b)                     #sum of entire array

820

# Vstack and hstack :  vertical stacking and horizontal stacking 


### vstack

place one array on top of the other: number of columns should match vstack

In [64]:
a=np.arange(1,21).reshape(4,5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [63]:
b=np.arange(21,41).reshape(4,5)
print(b)

[[21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]]


In [65]:
c=np.vstack((a,b))
print(c)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]]


In [77]:
#Another example

a=np.arange(1,19).reshape(3,6)
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


In [74]:
b=np.arange(19,37).reshape(3,6)
print(b)

[[19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


In [78]:
c=np.vstack((a,b))
print(c)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


### hstack

horizontal stacking: one next to the other . number of rows of the 2 arrays should match.


In [79]:
a=np.arange(1,21).reshape(4,5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [80]:
b=np.arange(21,41).reshape(4,5)
print(b)

[[21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]]


In [81]:
c=np.hstack((a,b))
print(c)

[[ 1  2  3  4  5 21 22 23 24 25]
 [ 6  7  8  9 10 26 27 28 29 30]
 [11 12 13 14 15 31 32 33 34 35]
 [16 17 18 19 20 36 37 38 39 40]]


# Diag function

In [82]:
a=np.diag([1,4,6,8])
print(a)

[[1 0 0 0]
 [0 4 0 0]
 [0 0 6 0]
 [0 0 0 8]]


In [83]:
b=np.diag([6,7])
print(b)

[[6 0]
 [0 7]]


# Ravel

used to convert 2D array to 1D

In [84]:
a=np.array([[1,3,5],[6,7,8]])
print(a)
print(a.ndim)

[[1 3 5]
 [6 7 8]]
2


In [85]:
b=a.ravel()
print(b)
print(b.ndim)

[1 3 5 6 7 8]
1


In [86]:
a=np.array([[[1,3,5],[6,7,8]]])     #3d array
print(a)
print(a.ndim)

[[[1 3 5]
  [6 7 8]]]
3


In [88]:
b=a.ravel()
print(b)
print(b.ndim)

[1 3 5 6 7 8]
1


# Transpose

In [89]:
#convert rows into coloumn

a=np.array([[1,5,7],[5,7,9]])
print(a)
print(a.shape)

[[1 5 7]
 [5 7 9]]
(2, 3)


In [91]:
b=a.T          #T for tranpose
print(b)
print(b.shape)

[[1 5]
 [5 7]
 [7 9]]
(3, 2)


In [92]:
a=np.array([[1,5,7],[9,11,13]])
print(a)
print(a.shape)

[[ 1  5  7]
 [ 9 11 13]]
(2, 3)


In [93]:
b=a.T          #T for tranpose
print(b)
print(b.shape)

[[ 1  9]
 [ 5 11]
 [ 7 13]]
(3, 2)


# abs

always return positive value

In [94]:
a=np.abs(-45)
a

45

In [96]:
a=np.abs(87)
a

87

# Concatination

Adding

In [99]:
a=np.array([[1,2,3,4],[5,6,7,8]])
b=np.array([[11,12,13,14],[15,16,17,18]])

print("a=",a)
print("b=",b)

print("\nAfter concatination")

c=np.concatenate([a,b])               #its like vstack
print(c)

a= [[1 2 3 4]
 [5 6 7 8]]
b= [[11 12 13 14]
 [15 16 17 18]]

After concatination
[[ 1  2  3  4]
 [ 5  6  7  8]
 [11 12 13 14]
 [15 16 17 18]]


# indentity matrix

The identity array is a square array with ones on the main diagonal.

In [101]:
a=np.eye(3,4,dtype=np.int64)
a

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]], dtype=int64)

# Numpy.full

In [102]:
a = np.full((4,5) ,8, dtype = np.int64)
print(a)

[[8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]]


In [104]:
a = np.full((7,5) ,55, dtype = np.int64)
print(a)

[[55 55 55 55 55]
 [55 55 55 55 55]
 [55 55 55 55 55]
 [55 55 55 55 55]
 [55 55 55 55 55]
 [55 55 55 55 55]
 [55 55 55 55 55]]


# How to change the value in array

In [114]:
a=np.array([[1,3,5,7],[8,9,6,7]])
print("before changing value:",a)
b=a
b[1][2]=88
print("\nAfter",b)

before changing value: [[1 3 5 7]
 [8 9 6 7]]

After [[ 1  3  5  7]
 [ 8  9 88  7]]


# How to check the version of numpy

In [115]:
print(np.__version__)

1.23.5


# Math operations

In [120]:
x = np.array([[111,112],[121,122]], dtype=np.int64)
y = np.array([[211.1,212.1],[221.1,222.1]], dtype=np.float64)

print('X= ' , x)
print()
print('Y=' , y)

X=  [[111 112]
 [121 122]]

Y= [[211.1 212.1]
 [221.1 222.1]]


In [122]:
c=np.add(x,y)
print(c)              #111+211.1=322.1,112+212.1=324.1
                      #121+221.1=342.1,122+222.1=344.1

[[322.1 324.1]
 [342.1 344.1]]
